# Site settings
title: 72 Frameworks
description: > # this means to ignore newlines until "baseurl:"
  An attempt to document the evolving world of Javascript frameworks and what their benefits and offers are, in particular the smaller, less well-known ones.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rrees.github.io/72-frameworks/" # the base hostname & protocol for your site
twitter_username: rrees
github_username:  rrees

# Build settings
markdown: kramdown
